const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
module.exports = async ({ run, until, pause, window, root }) => {
  window.setSize(1120, 780);
  window.webContents.focus();
  for (const file of ['src/features/appCenter/app-center.css', 'src/components/global-tooltip.css']) await window.webContents.insertCSS(fs.readFileSync(path.join(root, file), 'utf8'));
  await window.webContents.insertCSS('.app { width: 100% !important; } .test-center-layout{display:flex;height:calc(100vh - 36px)}.test-center-layout>.chat-panel{flex:1;min-width:0}');
  await run(`
    window.centerEvents=[]; window.centerSent=[];
    window.cardbushDesktop.openExternal = async url => { centerEvents.push(['external',url]); };
    window.cardbushDesktop.isMaximized = async () => false;
    window.centerHost={id:'fixture',environmentId:'cloud-demo', plugins:[{id:'demo',name:'Design plugin',description:'Design workspace',longDescription:'Design workspace',version:'1.0.0',developerName:'Fixture',category:'Tools',keywords:[],capabilities:[],defaultPrompts:[],installed:true,enabled:true,logoPath:'',logoDarkPath:'',manifestPath:'',components:[{kind:'app',id:'canvas',name:'Design canvas',app:{kind:'url',url:'https://example.test/canvas'}},{kind:'app',id:'slack',name:'Slack',mcp:{registeredAppId:'slack'}},{kind:'runtime',id:'demo',runtime:{settings:true}}]}],pluginCommands:[]};
    window.cardbushDesktop.agents={connect:async()=>({}),call:async()=>({plugins:centerHost.plugins})};
    window.centerSidebarProps={language:'zh',section:'chat',activeConversationId:'draft',projects:[],conversations:[],changeReportsByConversation:{},
      onSectionChange:()=>{},onConversationChange:()=>{},onCreateConversation:()=>centerEvents.push(['new']),onAddProject:()=>{},onProjectAction:()=>{},
      onDeleteConversation:()=>{},onRenameConversation:async()=>true,onOpenConversationChanges:()=>{},onOpenSettings:()=>{},onOpenSearch:()=>centerEvents.push(['search'])};
    window.centerMenus=views.applicationMenus('zh',{newConversation:()=>centerEvents.push(['new']),openAppCenter:views.requestAppCenter,
      openPlugins:()=>centerEvents.push(['plugins']),openAutomations:()=>centerEvents.push(['automations']),openSettings:()=>centerEvents.push(['settings']),
      showShortcuts:()=>{},openDiagnostics:()=>{},toggleSidebar:()=>{},toggleInspector:()=>{},search:()=>{},openBrowser:()=>{}},
      {sidebarVisible:true,inspectorVisible:false,native:false,externalLinks:false});
    window.mountCenter=()=>renderView(h(views.ConversationHostContext.Provider,{value:centerHost},h(views.AppCenterProvider,{language:'zh',onNavigate:(app,environment)=>centerEvents.push(['navigate',app.id,environment])},
      h(views.GlobalTooltip),h(views.WindowFrame,{language:'zh',sidebarCollapsed:false,onToggleSidebar:()=>{},menus:centerMenus,onError:error=>failures.push(String(error))}),
      h('div',{className:'test-center-layout'},h(views.ChatSidebar,centerSidebarProps),h('main',{className:'main-stage'},h(views.ChatPanel,chatProps))))));
    Object.assign(chatProps,{language:'zh',loading:false,historyLoading:false,draft:'',availableModels:[{id:'fixture',modelName:'fixture',provider:'fixture',enabled:true}],
      onDraftChange:draft=>{chatProps.draft=draft;mountCenter();},onSend:async text=>{centerSent.push(text);chatProps.draft='';mountCenter();}});
    window.viewTheme='theme-bright'; mountCenter();
    window.centerClick=label=>{const target=[...document.querySelectorAll('button')].find(button=>button.getAttribute('aria-label')===label||button.getAttribute('title')===label||button.textContent.trim()===label);if(!target)throw Error('missing '+label);target.click();};
    window.centerInput=(label,value)=>{const node=document.querySelector('input[aria-label="'+label+'"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));};
    window.centerDrag=(source,target)=>{const from=document.querySelector(source),to=document.querySelector(target),dataTransfer=new DataTransfer();from.dispatchEvent(new DragEvent('dragstart',{dataTransfer,bubbles:true,cancelable:true}));to.dispatchEvent(new DragEvent('dragover',{dataTransfer,bubbles:true,cancelable:true}));to.dispatchEvent(new DragEvent('drop',{dataTransfer,bubbles:true,cancelable:true}));from.dispatchEvent(new DragEvent('dragend',{dataTransfer,bubbles:true}));};
    undefined;
  `);
  await until("!!document.querySelector('.app-center-launcher')", 'new app dock mounted');
  await pause(150);
  assert.equal(await run("document.querySelectorAll('.sidebar-nav .nav-row').length"), 1, await run("JSON.stringify({errors:failures,html:document.body.innerHTML.slice(0,2200)})"));
  assert.equal(await run("!!document.querySelector('.sidebar-footer .settings-dock,.sidebar-footer .sidebar-search-button')"), false);
  assert.equal(await run("getComputedStyle(document.querySelector('[data-shortcut=searchConversations]')).opacity"), '1');
  await run("document.querySelector('[data-shortcut=searchConversations]').click()");
  assert.deepEqual(await run('centerEvents'), [['search']]);
  await run("document.querySelector('.app-center-launcher').focus();centerClick('应用中心')");
  await until("document.querySelector('.app-center-drawer')?.open && document.querySelector('.app-center-drawer')?.dataset.visible==='true'", 'drawer opened');
  assert.equal(await run("document.querySelectorAll('.app-center-tile').length"), 4);
  assert.equal(await run("document.activeElement.getAttribute('aria-label')"), '搜索应用');
  assert.equal(await run('centerEvents.length'), 1, 'opening the center cannot execute an app');
  await pause(230);
  const output = path.join(root,'tmp'); fs.mkdirSync(output,{recursive:true});
  fs.writeFileSync(path.join(output,'app-center-bright.png'),(await window.webContents.capturePage()).toPNG());
  assert.equal(await run("!!document.querySelector('[aria-label=\"编辑快捷方式\"]')"), false);
  assert.equal(await run("document.querySelectorAll('.app-center-content select').length"), 0, 'display modes use theme-aware buttons');
  assert.equal(await run("document.querySelectorAll('.app-center-tile[data-application-id=\"plugin:demo:slack\"]').length"), 0, 'connector declarations do not create apps');
  await run("centerDrag('.app-center-drop-zone [data-application-id=\"builtin:plugins\"] button','.app-center-drop-zone [data-application-id=\"builtin:automations\"]')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts[1]==='builtin:plugins'", 'dragging onto next item moves after it');
  await run("centerDrag('.app-center-drop-zone [data-application-id=\"builtin:plugins\"] button','.app-center-drop-zone [data-application-id=\"builtin:automations\"]')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts[0]==='builtin:plugins'", 'dragging back onto previous item moves before it');
  await run("centerDrag('.app-center-tile[data-application-id=\"builtin:settings\"] .app-center-tile-open','.app-center-drop-zone')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts.includes('builtin:settings')", 'pin saved');
  await run("centerDrag('.app-center-drop-zone [data-application-id=\"builtin:settings\"] button','.app-center-drop-zone [data-application-id=\"builtin:automations\"]')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts[1]==='builtin:settings'", 'reorder saved');
  await run("centerClick('悬停展开')");
  await until("document.querySelector('.app-center-dock').dataset.display==='hover'", 'hover mode applied');
  await run("centerClick('添加应用链接')");
  await run("centerInput('应用名称','本地看板');centerInput('应用地址','http://localhost:8888/dashboard');");
  await pause(40); await run("document.querySelector('.app-center-link-form').requestSubmit()");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).links.length===1", 'external app persisted');
  await run("centerClick('关闭应用中心')");
  await until("!document.querySelector('.app-center-drawer')", 'animated close completes');
  assert.equal(await run("document.activeElement.className"), 'app-center-launcher');
  await run("centerDrag('.app-center-dock [data-application-id=\"builtin:settings\"] button','.app-center-dock [data-application-id=\"builtin:plugins\"]')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts[0]==='builtin:settings'", 'dock supports direct drag');
  assert.equal(await run('centerEvents.length'),1,'dragging must not launch an application');
  await run("document.querySelector('.app-center-launcher').focus()"); await pause(230);
  assert.ok(await run("(() => {const dock=document.querySelector('.app-center-dock').getBoundingClientRect(),left=document.querySelector('.app-center-launcher').getBoundingClientRect().left,right=document.querySelector('.app-center-shortcuts').getBoundingClientRect().right;return Math.abs((left+right)/2-(dock.left+dock.right)/2)<2})()"),'dock contents are centered as a group');
  await run("document.querySelector('textarea[data-composer-input]').focus()");
  window.webContents.sendInputEvent({type:'mouseMove',x:700,y:400}); await pause(250);
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-shortcuts')).visibility"), 'hidden');
  await run("document.querySelector('.app-center-launcher').focus()"); await pause(210);
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-shortcuts')).visibility"), 'visible', 'keyboard users reveal hover shortcuts');
  const launcher = await run("(() => {const r=document.querySelector('.app-center-launcher').getBoundingClientRect();return {x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)}})()");
  window.webContents.sendInputEvent({type:'mouseMove',...launcher});
  await until("!!document.querySelector('.global-tooltip')", 'hover shortcut tooltip visible');
  assert.equal(await run("document.querySelector('.global-tooltip kbd').textContent"), 'Ctrl + Shift + A');
  assert.equal(await run("getComputedStyle(document.querySelector('.global-tooltip')).borderRadius"), '999px');
  assert.equal(await run("document.querySelector('.app-center-launcher').hasAttribute('title')"), false, 'no duplicate native tooltip');
  await run("views.saveKeyboardShortcuts({openAppCenter:{key:'k',ctrl:true,shift:true}})");
  window.webContents.sendInputEvent({type:'mouseMove',x:700,y:400}); await pause(30);
  window.webContents.sendInputEvent({type:'mouseMove',...launcher});
  await until("document.querySelector('.global-tooltip kbd')?.textContent==='Ctrl + Shift + K'", 'tooltip follows user key binding');
  await run("document.querySelector('textarea[data-composer-input]').focus();window.dispatchEvent(new KeyboardEvent('keydown',{key:'K',ctrlKey:true,shiftKey:true,bubbles:true,cancelable:true}))");
  await until("document.querySelector('.app-center-drawer')?.open", 'custom app center shortcut works');
  await run("window.viewTheme='theme-dark';mountCenter()"); await pause(260);
  assert.ok(await run("getComputedStyle(document.querySelector('.app-center-drawer')).backgroundColor !== 'rgb(255, 255, 255)'"));
  fs.writeFileSync(path.join(output,'app-center-dark.png'),(await window.webContents.capturePage()).toPNG());
  await run("centerClick('本地看板')");
  await until("centerEvents.some(event=>event[0]==='external')", 'external app opens only on click');
  assert.deepEqual(await run("centerEvents.find(event=>event[0]==='external')"), ['external','http://localhost:8888/dashboard']);
  await until("!document.querySelector('.app-center-drawer')", 'drawer closed after launch');
  await run("const input=document.querySelector('textarea[data-composer-input]');input.focus();Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(input,'@定时');input.setSelectionRange(3,3);input.dispatchEvent(new Event('input',{bubbles:true}));");
  await until("!!document.querySelector('[data-command-id=\"application:builtin:automations\"]')", 'app appears in mention menu');
  const before=await run('centerEvents.length');
  await run("document.querySelector('[data-command-id=\"application:builtin:automations\"]').dispatchEvent(new MouseEvent('mousedown',{bubbles:true,cancelable:true}))");
  await pause(120);
  assert.match(await run('chatProps.draft'), /cardbush-reference:\/\/application/, await run("JSON.stringify({draft:chatProps.draft,textarea:document.querySelector('[data-composer-input]')?.outerHTML})"));
  await until("!!document.querySelector('[data-context-reference]')", 'application chip inserted');
  assert.match(await run('chatProps.draft'), /cardbush-reference:\/\/application/);
  assert.equal(await run('centerEvents.length'),before,'mention does not launch app');
  await run("document.querySelector('.send-button').click()");
  await until('centerSent.length===1','application reference submitted');
  assert.match(await run('centerSent[0]'),/builtin%3Aautomations/);
  await run("views.requestApplication('plugin:demo:canvas','cloud-demo',{applicationKind:'plugin',title:'Design canvas',target:'demo',componentId:'canvas'})");
  await until("centerEvents.at(-1)?.[1]==='https://example.test/canvas'", 'remote app opens its verified page URL');
  assert.deepEqual(await run('centerEvents.at(-1)'),['external','https://example.test/canvas']);
  await run("views.requestAppCenter()");
  await until("document.querySelector('.app-center-drawer')?.open", 'reopen preserves preferences');
  await run("centerClick('固定到快捷方式 本地看板')");
  await until("document.querySelectorAll('.app-center-dock .app-center-shortcut').length===4", 'four shortcuts visible');
  assert.ok(await run("(() => {const node=document.querySelector('.app-center-shortcuts');return node.scrollWidth<=node.clientWidth})()"),'four shortcuts fit a narrow sidebar without distorting icons');
  await run("centerClick('固定到快捷方式 Design canvas')");
  await until("document.querySelector('.app-center-error')?.textContent.includes('最多')", 'pin limit is explicit');
  assert.equal(await run("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts.length"),4);
  await run("centerClick('编辑 本地看板')");
  await until("!!document.querySelector('.app-center-link-form')", 'edit link');
  await run("centerInput('应用名称','团队看板');centerInput('应用地址','https://example.test/dashboard')");
  await run("document.querySelector('.app-center-link-form').requestSubmit()");
  await until("!!document.querySelector('.app-center-shortcut[aria-label=团队看板]')", 'editing preserves the pinned identity');
  await run("centerClick('删除 团队看板')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).links.length===0", 'deletion removes link');
  assert.equal(await run("document.querySelectorAll('.app-center-dock .app-center-shortcut').length"),3);
  await run("centerDrag('.app-center-tile[data-application-id=\"plugin:demo:canvas\"] .app-center-tile-open','.app-center-tile[data-application-id=\"builtin:plugins\"]')");
  await until("document.querySelector('.app-center-tile').dataset.applicationId==='plugin:demo:canvas'", 'application grid drag order persisted');
  window.webContents.sendInputEvent({type:'keyDown',keyCode:'Tab'});window.webContents.sendInputEvent({type:'keyUp',keyCode:'Tab'});
  assert.ok(await run("!!document.activeElement.closest('.app-center-drawer')"),'Tab focus stays in drawer');
  await run("document.querySelector('.app-center-drawer').dispatchEvent(new Event('cancel',{cancelable:true}));views.requestAppCenter()");
  await pause(260);
  assert.ok(await run("document.querySelector('.app-center-drawer')?.open"),'quick reopen survives the previous exit timer');
  window.setSize(480,640);await pause(80);
  assert.ok(await run("(() => {const node=document.querySelector('.app-center-drawer'),r=node.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=36&&r.bottom<=innerHeight&&node.scrollWidth<=node.clientWidth})()"),'drawer fits a narrow window');
  window.webContents.sendInputEvent({type:'mouseDown',x:465,y:80,button:'left',clickCount:1});
  window.webContents.sendInputEvent({type:'mouseUp',x:465,y:80,button:'left',clickCount:1});
  await until("!document.querySelector('.app-center-drawer')",'backdrop closes the drawer');
  window.webContents.debugger.attach('1.3');
  await window.webContents.debugger.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await run("views.requestAppCenter()");
  await until("document.querySelector('.app-center-drawer')?.open",'drawer opens with reduced motion');
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-drawer')).transitionDuration"),'0s');
  window.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});window.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});
  await until("!document.querySelector('.app-center-drawer')",'Escape closes the drawer');
  window.webContents.debugger.detach();
  await run('renderView(null)');await pause(30);await run('mountCenter()');
  await until("document.querySelector('.app-center-dock')?.dataset.display==='hover'",'remount restores saved display mode');
  assert.equal(await run("document.querySelectorAll('.app-center-dock .app-center-shortcut').length"),3);
  console.log('App center UI passed: drawer, themes, focus, shortcuts, persistence, link editing/deletion, narrow windows, rapid reopen, reduced motion, shortcut hints and non-executing cloud @ references.');
};
