const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
module.exports = async ({ run, until, pause, window, root }) => {
  window.setSize(1120, 780);
  window.webContents.focus();
  for (const file of ['src/features/appCenter/app-center.css', 'src/components/global-tooltip.css']) await window.webContents.insertCSS(fs.readFileSync(path.join(root, file), 'utf8'));
  await window.webContents.insertCSS('.app { width: 100% !important; } .test-center-layout{display:flex;height:calc(100vh - 36px)}.test-center-layout>.chat-panel{flex:1;min-width:0}');
  const localAppIcon = 'data:image/png;base64,' + fs.readFileSync(path.join(root, 'assets/plugins/chrome/extension/icons/cardbush-32.png')).toString('base64');
  await run(`
    window.centerEvents=[]; window.centerSent=[];
    window.cardbushDesktop.openExternal = async url => { centerEvents.push(['external',url]); };
    window.localAppFixture={id:'local:editor',title:'本地编辑器',path:'C:/Program Files/编辑器/editor.exe',icon:${JSON.stringify(localAppIcon)}};
    window.localSelection=null; window.localOpened=[]; window.localPickLanguages=[]; window.localOpenError='';
    window.cardbushDesktop.localApplications={pick:async language=>{localPickLanguages.push(language);return localSelection;},open:async target=>{if(localOpenError)throw Error(localOpenError);localOpened.push(target);}};
    window.cardbushDesktop.isMaximized = async () => false;
    window.centerHost={id:'fixture',environmentId:'cloud-demo', plugins:[{id:'demo',name:'Design plugin',description:'Design workspace',longDescription:'Design workspace',version:'1.0.0',developerName:'Fixture',category:'Tools',keywords:[],capabilities:[],defaultPrompts:[],installed:true,enabled:true,logoPath:'',logoDarkPath:'',manifestPath:'',components:[{kind:'app',id:'canvas',name:'Design canvas',app:{kind:'url',url:'https://example.test/canvas'}},{kind:'app',id:'slack',name:'Slack',mcp:{registeredAppId:'slack'}},{kind:'runtime',id:'demo',runtime:{settings:true}}]}],pluginCommands:[]};
    window.cardbushDesktop.agents={connect:async()=>({}),call:async()=>({plugins:centerHost.plugins})};
    window.centerSidebarProps={language:'zh',section:'chat',activeConversationId:'draft',projects:[],conversations:[],changeReportsByConversation:{},
      onSectionChange:()=>{},onConversationChange:()=>{},onCreateConversation:()=>centerEvents.push(['new']),onAddProject:()=>{},onProjectAction:()=>{},
      onDeleteConversation:()=>{},onRenameConversation:async()=>true,onOpenConversationChanges:()=>{},onOpenSettings:()=>{},onOpenSearch:()=>centerEvents.push(['search'])};
    window.centerMenus=views.applicationMenus('zh',{newConversation:()=>centerEvents.push(['new']),openAppCenter:views.requestAppCenter,
      openPlugins:()=>centerEvents.push(['plugins']),openAutomations:()=>centerEvents.push(['automations']),openSettings:()=>centerEvents.push(['settings']),
      showShortcuts:()=>{},openDiagnostics:()=>{},toggleSidebar:()=>{},toggleInspector:()=>{},search:()=>{},openBrowser:()=>{}},
      {sidebarVisible:true,inspectorVisible:false,native:false,externalLinks:false});
    window.mountCenter=()=>renderView(h(views.ConversationHostContext.Provider,{value:centerHost},h(views.AppCenterProvider,{language:'zh',onNavigate:(app,environment)=>centerEvents.push(['navigate',app.id,environment])},
      h(views.GlobalTooltip),h(views.WindowFrame,{language:'zh',sidebarCollapsed:false,onToggleSidebar:()=>{},menus:centerMenus,onError:error=>failures.push(String(error))}),
      h('div',{className:'test-center-layout'},h(views.ChatSidebar,centerSidebarProps),h('main',{className:'main-stage'},h(views.ChatPanel,chatProps))))));
    Object.assign(chatProps,{language:'zh',loading:false,historyLoading:false,draft:'',availableModels:[{id:'fixture',modelName:'fixture',provider:'fixture',enabled:true}],
      onDraftChange:draft=>{chatProps.draft=draft;mountCenter();},onSend:async text=>{centerSent.push(text);chatProps.draft='';mountCenter();}});
    window.viewTheme='theme-bright'; mountCenter();
    window.centerClick=label=>{const target=[...document.querySelectorAll('button')].find(button=>button.getAttribute('aria-label')===label||button.getAttribute('title')===label||button.textContent.trim()===label);if(!target)throw Error('missing '+label);target.click();};
    window.centerInput=(label,value)=>{const node=document.querySelector('input[aria-label="'+label+'"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));};
    window.centerStartDrag=source=>{window.centerDragSource=document.querySelector(source);window.centerTransfer=new DataTransfer();centerTransfer.setDragImage=(node,x,y)=>{window.centerDragImage={text:node.textContent,icons:node.querySelectorAll('svg,img').length,width:node.getBoundingClientRect().width,x,y};};centerDragSource.dispatchEvent(new DragEvent('dragstart',{dataTransfer:centerTransfer,bubbles:true,cancelable:true}));};
    window.centerFinishDrag=target=>{const to=target&&document.querySelector(target);if(to){to.dispatchEvent(new DragEvent('dragover',{dataTransfer:centerTransfer,bubbles:true,cancelable:true}));to.dispatchEvent(new DragEvent('drop',{dataTransfer:centerTransfer,bubbles:true,cancelable:true}));}centerDragSource.dispatchEvent(new DragEvent('dragend',{dataTransfer:centerTransfer,bubbles:true}));};
    window.centerDrag=async(source,target)=>{centerStartDrag(source);await new Promise(resolve=>setTimeout(resolve,60));centerFinishDrag(target);};
    undefined;
  `);
  await until("!!document.querySelector('.app-center-launcher')", 'new app dock mounted');
  await pause(150);
  assert.equal(await run("document.querySelectorAll('.sidebar-nav .nav-row').length"), 1, await run("JSON.stringify({errors:failures,html:document.body.innerHTML.slice(0,2200)})"));
  assert.equal(await run("!!document.querySelector('.sidebar-footer .settings-dock,.sidebar-footer .sidebar-search-button')"), false);
  assert.equal(await run("getComputedStyle(document.querySelector('[data-shortcut=searchConversations]')).opacity"), '1');
  await run("document.querySelector('[data-shortcut=searchConversations]').click()");
  assert.deepEqual(await run('centerEvents'), [['search']]);
  await run("document.querySelector('.app-center-launcher').focus();centerClick('应用中心')");
  await until("document.querySelector('.app-center-drawer')?.open && document.querySelector('.app-center-drawer')?.dataset.visible==='true'", 'drawer opened');
  assert.equal(await run("document.querySelectorAll('.app-center-tile').length"), 4);
  assert.equal(await run("document.activeElement.getAttribute('aria-label')"), '搜索应用');
  assert.equal(await run('centerEvents.length'), 1, 'opening the center cannot execute an app');
  await pause(230);
  const output = path.join(root,'tmp'); fs.mkdirSync(output,{recursive:true});
  fs.writeFileSync(path.join(output,'app-center-bright.png'),(await window.webContents.capturePage()).toPNG());
  assert.equal(await run("!!document.querySelector('[aria-label=\"编辑快捷方式\"]')"), false);
  assert.equal(await run("document.querySelectorAll('.app-center-content select').length"), 0, 'display modes use theme-aware buttons');
  assert.equal(await run("document.querySelectorAll('.app-center-tile small,.app-center-dock-editor,.app-center-drop-zone').length"), 0, 'drawer shows no descriptions or duplicate sorting area');
  assert.equal(await run("document.querySelectorAll('.app-center-tile[data-application-id=\"plugin:demo:slack\"]').length"), 0, 'connector declarations do not create apps');
  await run("centerClick('关闭应用中心')");
  await until("!document.querySelector('.app-center-drawer')", 'close drawer before reordering dock');
  await run("centerDrag('.app-center-dock [data-application-id=\"builtin:plugins\"] button','.app-center-dock [data-application-id=\"builtin:automations\"]')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts[1]==='builtin:plugins'", 'dragging onto next item moves after it');
  await run("centerDrag('.app-center-dock [data-application-id=\"builtin:plugins\"] button','.app-center-dock [data-application-id=\"builtin:automations\"]')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts[0]==='builtin:plugins'", 'dragging back onto previous item moves before it');
  await run("views.requestAppCenter()");
  await until("!!document.querySelector('.app-center-drawer:modal')", 'reopen drawer for drag to dock');
  await run("centerStartDrag('.app-center-tile[data-application-id=\"builtin:settings\"] .app-center-tile-open')");
  await until("document.querySelector('.app-center-drawer')?.dataset.dragging==='true' && !document.querySelector('.app-center-drawer:modal')", 'drag releases modal dock blocking');
  await pause(220);
  assert.deepEqual(await run('centerDragImage'), {text:'',icons:1,width:36,x:18,y:18}, 'drag preview contains only one icon');
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-drawer')).filter"), 'blur(3px)');
  assert.ok(await run("Number(getComputedStyle(document.querySelector('.app-center-drawer')).opacity)<0.5"), 'drawer fades during drag');
  assert.ok(await run("(() => {const dock=document.querySelector('.app-center-dock'),r=dock.getBoundingClientRect();return dock.contains(document.elementFromPoint(r.left+r.width/2,r.top+r.height/2))})()"), 'real dock receives pointer hits outside drawer');
  fs.writeFileSync(path.join(output,'app-center-drag.png'),(await window.webContents.capturePage()).toPNG());
  await run("centerFinishDrag('.app-center-dock')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts.includes('builtin:settings')", 'pin saved');
  await until("!!document.querySelector('.app-center-drawer:modal')", 'drop restores modal focus scope');
  assert.equal(await run("!!document.querySelector('.app-center-drag-preview')"), false, 'drop cleans drag preview');
  await run("centerStartDrag('.app-center-tile[data-application-id=\"builtin:plugins\"] .app-center-tile-open')");
  await until("document.querySelector('.app-center-drawer')?.dataset.dragging==='true'", 'second drag starts');
  await run('centerFinishDrag()');
  await until("!!document.querySelector('.app-center-drawer:modal') && document.querySelector('.app-center-drawer').dataset.dragging==='false'", 'cancel restores drawer');
  assert.deepEqual(await run("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts"), ['builtin:plugins','builtin:automations','builtin:settings'], 'cancel preserves order');
  // Exercise Chromium's native dragstart and hit testing, including the modal
  // handoff; synthetic drops alone can reach otherwise inert elements.
  window.webContents.debugger.attach('1.3');
  let nativeDragData;
  const interceptDrag = (_event, method, params) => { if (method === 'Input.dragIntercepted') nativeDragData = params.data; };
  window.webContents.debugger.on('message', interceptDrag);
  try {
    await window.webContents.debugger.sendCommand('Input.setInterceptDrags', {enabled:true});
    const source = await run("(() => {const r=document.querySelector('.app-center-tile[data-application-id=\"plugin:demo:canvas\"] .app-center-tile-open').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}})()");
    await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', {type:'mouseMoved',...source});
    await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', {type:'mousePressed',...source,button:'left',buttons:1,clickCount:1});
    await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', {type:'mouseMoved',x:source.x+16,y:source.y+16,button:'left',buttons:1});
    await until("document.querySelector('.app-center-drawer')?.dataset.dragging==='true' && !document.querySelector('.app-center-drawer:modal')", 'native drag keeps running after modal release');
    for (let attempt=0;attempt<20&&!nativeDragData;attempt++) await pause(25);
    assert.ok(nativeDragData, 'Chromium intercepts a native drag');
    assert.equal(nativeDragData.items.find(item=>item.mimeType==='application/x-cardbush-app')?.data,'plugin:demo:canvas');
    const target = await run("(() => {const r=document.querySelector('.app-center-dock').getBoundingClientRect();return {x:r.right-8,y:r.top+r.height/2}})()");
    for (const type of ['dragEnter','dragOver','drop']) await window.webContents.debugger.sendCommand('Input.dispatchDragEvent', {type,...target,data:nativeDragData});
    await window.webContents.debugger.sendCommand('Input.dispatchMouseEvent', {type:'mouseReleased',...target,button:'left',buttons:0,clickCount:1});
    await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts.includes('plugin:demo:canvas') && !!document.querySelector('.app-center-drawer:modal')", 'native drag pins to the real dock and restores dialog');
    assert.equal(await run('centerEvents.length'),1,'native drag must not launch an application');
  } finally {
    await window.webContents.debugger.sendCommand('Input.setInterceptDrags', {enabled:false});
    window.webContents.debugger.removeListener('message', interceptDrag);
    window.webContents.debugger.detach();
  }
  await run("centerClick('取消固定 Design canvas')");
  await run("centerClick('关闭应用中心')");
  await until("!document.querySelector('.app-center-drawer')", 'close drawer to sort newly pinned app');
  await run("centerDrag('.app-center-dock [data-application-id=\"builtin:settings\"] button','.app-center-dock [data-application-id=\"builtin:automations\"]')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts[1]==='builtin:settings'", 'reorder saved');
  await run("views.requestAppCenter()");
  await until("!!document.querySelector('.app-center-drawer:modal')", 'reopen display settings');
  await run("centerClick('悬停展开')");
  await until("document.querySelector('.app-center-dock').dataset.display==='hover'", 'hover mode applied');
  await run("centerClick('添加应用链接')");
  await run("centerInput('应用名称','本地看板');centerInput('应用地址','http://localhost:8888/dashboard');");
  await pause(40); await run("document.querySelector('.app-center-link-form').requestSubmit()");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).links.length===1", 'external app persisted');
  await run("centerClick('关闭应用中心')");
  await until("!document.querySelector('.app-center-drawer')", 'animated close completes');
  assert.equal(await run("document.activeElement.className"), 'app-center-launcher');
  await run("centerDrag('.app-center-dock [data-application-id=\"builtin:settings\"] button','.app-center-dock [data-application-id=\"builtin:plugins\"]')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts[0]==='builtin:settings'", 'dock supports direct drag');
  assert.equal(await run('centerEvents.length'),1,'dragging must not launch an application');
  await run("document.querySelector('.app-center-launcher').focus()"); await pause(230);
  await run("document.querySelector('textarea[data-composer-input]').focus()");
  window.webContents.sendInputEvent({type:'mouseMove',x:700,y:400});
  await until("getComputedStyle(document.querySelector('.app-center-shortcuts')).visibility==='hidden'", 'shortcuts collapse after leaving the dock');
  await run("document.querySelector('.app-center-launcher').focus()"); await pause(210);
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-shortcuts')).visibility"), 'hidden', 'programmatic focus alone cannot reveal hover shortcuts');
  for (const modifiers of [['shift'], []]) {
    window.webContents.sendInputEvent({type:'keyDown',keyCode:'Tab',modifiers});
    window.webContents.sendInputEvent({type:'keyUp',keyCode:'Tab',modifiers});
    await pause(30);
  }
  assert.equal(await run("document.activeElement.className"), 'app-center-launcher', 'native Tab navigation reaches the launcher');
  await pause(210);
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-shortcuts')).visibility"), 'visible', 'keyboard users reveal hover shortcuts');
  assert.ok(await run("(() => {const dock=document.querySelector('.app-center-dock').getBoundingClientRect(),left=document.querySelector('.app-center-launcher').getBoundingClientRect().left,right=document.querySelector('.app-center-shortcuts').getBoundingClientRect().right;return Math.abs(left-dock.left)<1&&Math.abs(right-dock.right)<1})()"),'launcher aligns left and app shortcuts align right');
  await until("document.querySelector('.global-tooltip')?.textContent.includes('应用中心')", 'keyboard navigation still reveals accessible help');
  await run(`
    window.centerReactivate=()=>{
      window.dispatchEvent(new Event('blur'));
      window.dispatchEvent(new Event('focus'));
      document.querySelector('.app-center-launcher').dispatchEvent(new FocusEvent('focusin',{bubbles:true}));
    };
    centerReactivate();
    document.querySelector('.app-center-launcher').dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',altKey:true,bubbles:true}));
  `);
  await pause(500);
  assert.equal(await run("document.activeElement.className"), 'app-center-launcher', 'window reactivation preserves the focus position');
  assert.equal(await run("!!document.querySelector('.global-tooltip')"), false, 'restored focus and Alt+Tab do not summon a tooltip');
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-shortcuts')).visibility"), 'hidden', 'restored focus does not expand shortcuts');
  const launcher = await run("(() => {const r=document.querySelector('.app-center-launcher').getBoundingClientRect();return {x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)}})()");
  await run("document.querySelector('textarea[data-composer-input]').focus()");
  window.webContents.sendInputEvent({type:'mouseMove',...launcher});
  await until("document.querySelector('.app-center-dock').dataset.hoverExpanded==='true'", 'pointer enters the dock');
  await until("getComputedStyle(document.querySelector('.app-center-shortcuts')).opacity==='1'", 'pointer reveals shortcuts without keyboard focus');
  window.webContents.sendInputEvent({type:'mouseMove',x:700,y:400}); await pause(350);
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-shortcuts')).opacity"), '1', 'briefly overshooting the dock keeps shortcuts fully visible');
  window.webContents.sendInputEvent({type:'mouseMove',...launcher}); await pause(1000);
  fs.writeFileSync(path.join(output,'app-center-dock-alignment.png'),(await window.webContents.capturePage()).toPNG());
  window.webContents.sendInputEvent({type:'mouseMove',x:700,y:400}); await pause(350);
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-shortcuts')).opacity"), '1', 'returning cancels the old timer and the next exit gets a full hold');
  await until("getComputedStyle(document.querySelector('.app-center-shortcuts')).visibility==='hidden'", 'shortcuts eventually collapse after the hold');
  assert.equal(await run("document.querySelector('.app-center-launcher').getBoundingClientRect().left === document.querySelector('.app-center-dock').getBoundingClientRect().left"),true,'collapsing shortcuts does not move the launcher');
  window.webContents.sendInputEvent({type:'mouseMove',...launcher});
  await until("!!document.querySelector('.global-tooltip')", 'hover shortcut tooltip visible');
  assert.equal(await run("document.querySelector('.global-tooltip kbd').textContent"), 'Ctrl + Shift + A');
  assert.equal(await run("getComputedStyle(document.querySelector('.global-tooltip')).borderRadius"), '999px');
  assert.equal(await run("document.querySelector('.app-center-launcher').hasAttribute('title')"), false, 'no duplicate native tooltip');
  await run(`centerReactivate();document.querySelector('.app-center-launcher').dispatchEvent(new PointerEvent('pointerover',{bubbles:true,pointerType:'mouse',clientX:${launcher.x},clientY:${launcher.y}}));document.querySelector('.app-center-launcher').dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerType:'mouse',clientX:${launcher.x},clientY:${launcher.y}}));`);
  await pause(500);
  assert.equal(await run("!!document.querySelector('.global-tooltip')"), false, 'stationary pointer restoration does not summon a tooltip');
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-shortcuts')).visibility"), 'hidden', 'CSS hover cannot override the reset after returning to the window');
  window.webContents.sendInputEvent({type:'mouseMove',x:launcher.x+2,y:launcher.y});
  await until("!!document.querySelector('.global-tooltip') && document.querySelector('.app-center-dock').dataset.hoverExpanded==='true'", 'moving within the dock after returning restores normal hover');
  await require('./tooltip-activation.cjs')({ run, until, pause, window });
  await run("views.saveKeyboardShortcuts({openAppCenter:{key:'k',ctrl:true,shift:true}})");
  window.webContents.sendInputEvent({type:'mouseMove',x:700,y:400}); await pause(30);
  window.webContents.sendInputEvent({type:'mouseMove',...launcher});
  await until("document.querySelector('.global-tooltip kbd')?.textContent==='Ctrl + Shift + K'", 'tooltip follows user key binding');
  await run("document.querySelector('textarea[data-composer-input]').focus();window.dispatchEvent(new KeyboardEvent('keydown',{key:'K',ctrlKey:true,shiftKey:true,bubbles:true,cancelable:true}))");
  await until("document.querySelector('.app-center-drawer')?.open", 'custom app center shortcut works');
  await run("window.viewTheme='theme-dark';mountCenter()"); await pause(260);
  assert.ok(await run("getComputedStyle(document.querySelector('.app-center-drawer')).backgroundColor !== 'rgb(255, 255, 255)'"));
  fs.writeFileSync(path.join(output,'app-center-dark.png'),(await window.webContents.capturePage()).toPNG());
  await run("centerClick('本地看板')");
  await until("centerEvents.some(event=>event[0]==='external')", 'external app opens only on click');
  assert.deepEqual(await run("centerEvents.find(event=>event[0]==='external')"), ['external','http://localhost:8888/dashboard']);
  await until("!document.querySelector('.app-center-drawer')", 'drawer closed after launch');
  await run("const input=document.querySelector('textarea[data-composer-input]');input.focus();Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(input,'@定时');input.setSelectionRange(3,3);input.dispatchEvent(new Event('input',{bubbles:true}));");
  await until("!!document.querySelector('[data-command-id=\"application:builtin:automations\"]')", 'app appears in mention menu');
  const before=await run('centerEvents.length');
  await run("document.querySelector('[data-command-id=\"application:builtin:automations\"]').dispatchEvent(new MouseEvent('mousedown',{bubbles:true,cancelable:true}))");
  await pause(120);
  assert.match(await run('chatProps.draft'), /cardbush-reference:\/\/application/, await run("JSON.stringify({draft:chatProps.draft,textarea:document.querySelector('[data-composer-input]')?.outerHTML})"));
  await until("!!document.querySelector('[data-context-reference]')", 'application chip inserted');
  assert.match(await run('chatProps.draft'), /cardbush-reference:\/\/application/);
  assert.equal(await run('centerEvents.length'),before,'mention does not launch app');
  await run("document.querySelector('.send-button').click()");
  await until('centerSent.length===1','application reference submitted');
  assert.match(await run('centerSent[0]'),/builtin%3Aautomations/);
  await run("views.requestApplication('plugin:demo:canvas','cloud-demo',{applicationKind:'plugin',title:'Design canvas',target:'demo',componentId:'canvas'})");
  await until("centerEvents.at(-1)?.[1]==='https://example.test/canvas'", 'remote app opens its verified page URL');
  assert.deepEqual(await run('centerEvents.at(-1)'),['external','https://example.test/canvas']);
  await run("views.requestAppCenter()");
  await until("document.querySelector('.app-center-drawer')?.open", 'reopen preserves preferences');
  await run("centerClick('固定到快捷方式 本地看板')");
  await until("document.querySelectorAll('.app-center-dock .app-center-shortcut').length===4", 'four shortcuts visible');
  assert.ok(await run("(() => {const node=document.querySelector('.app-center-shortcuts');return node.scrollWidth<=node.clientWidth})()"),'four shortcuts fit a narrow sidebar without distorting icons');
  await run("centerClick('固定到快捷方式 Design canvas')");
  await until("document.querySelector('.app-center-error')?.textContent.includes('最多')", 'pin limit is explicit');
  assert.equal(await run("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts.length"),4);
  await run("centerClick('编辑 本地看板')");
  await until("!!document.querySelector('.app-center-link-form')", 'edit link');
  await run("centerInput('应用名称','团队看板');centerInput('应用地址','https://example.test/dashboard')");
  await run("document.querySelector('.app-center-link-form').requestSubmit()");
  await until("!!document.querySelector('.app-center-shortcut[aria-label=团队看板]')", 'editing preserves the pinned identity');
  await run("centerClick('删除 团队看板')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).links.length===0", 'deletion removes link');
  assert.equal(await run("document.querySelectorAll('.app-center-dock .app-center-shortcut').length"),3);
  await run("centerDrag('.app-center-tile[data-application-id=\"plugin:demo:canvas\"] .app-center-tile-open','.app-center-tile[data-application-id=\"builtin:plugins\"]')");
  assert.equal(await run("document.querySelector('.app-center-tile').dataset.applicationId"), 'builtin:plugins', 'drawer grid is not a sorting target');
  window.webContents.sendInputEvent({type:'keyDown',keyCode:'Tab'});window.webContents.sendInputEvent({type:'keyUp',keyCode:'Tab'});
  assert.ok(await run("!!document.activeElement.closest('.app-center-drawer')"),'Tab focus stays in drawer');
  await run("document.querySelector('.app-center-drawer').dispatchEvent(new Event('cancel',{cancelable:true}));views.requestAppCenter()");
  await pause(260);
  assert.ok(await run("document.querySelector('.app-center-drawer')?.open"),'quick reopen survives the previous exit timer');
  window.setSize(480,640);await pause(80);
  assert.ok(await run("(() => {const node=document.querySelector('.app-center-drawer'),r=node.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=36&&r.bottom<=innerHeight&&node.scrollWidth<=node.clientWidth})()"),'drawer fits a narrow window');
  window.webContents.sendInputEvent({type:'mouseDown',x:465,y:80,button:'left',clickCount:1});
  window.webContents.sendInputEvent({type:'mouseUp',x:465,y:80,button:'left',clickCount:1});
  await until("!document.querySelector('.app-center-drawer')",'backdrop closes the drawer');
  window.webContents.debugger.attach('1.3');
  await window.webContents.debugger.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await run("views.requestAppCenter()");
  await until("document.querySelector('.app-center-drawer')?.open",'drawer opens with reduced motion');
  assert.equal(await run("getComputedStyle(document.querySelector('.app-center-drawer')).transitionDuration"),'0s');
  window.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});window.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});
  await until("!document.querySelector('.app-center-drawer')",'Escape closes the drawer');
  window.webContents.debugger.detach();
  await run('renderView(null)');await pause(30);await run('mountCenter()');
  await until("document.querySelector('.app-center-dock')?.dataset.display==='hover'",'remount restores saved display mode');
  assert.equal(await run("document.querySelectorAll('.app-center-dock .app-center-shortcut').length"),3);
  window.setSize(1120,780);
  await run('views.requestAppCenter()');
  await until("!!document.querySelector('.app-center-drawer:modal')", 'open to add local app');
  await run("centerClick('添加本地应用')");
  await pause(40);
  assert.equal(await run("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).localApps?.length??0"),0,'canceling picker makes no entry');
  await run("localSelection=localAppFixture;centerClick('添加本地应用')");
  await until("!!document.querySelector('.app-center-tile[data-application-id=\"local:editor\"]')",'chosen local app appears');
  assert.deepEqual(await run('localOpened'),[],'adding an app never launches it');
  assert.deepEqual(await run('localPickLanguages'),['zh','zh']);
  assert.equal(await run("document.querySelector('.app-center-tile[data-application-id=\"local:editor\"] img').src"),await run('localAppFixture.icon'),'native icon is displayed');
  await run("centerClick('添加本地应用')");await pause(40);
  assert.equal(await run("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).localApps.length"),1,'adding same local app is idempotent');
  await run("centerClick('固定到快捷方式 本地编辑器');centerClick('关闭应用中心')");
  await until("!document.querySelector('.app-center-drawer')",'close before sorting local dock icon');
  await run("centerDrag('.app-center-dock [data-application-id=\"local:editor\"] button','.app-center-dock [data-application-id=\"builtin:settings\"]')");
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).shortcuts[0]==='local:editor'",'local app can be sorted in dock');
  await run('renderView(null)');await pause(30);await run('mountCenter()');
  await until("!!document.querySelector('.app-center-dock [data-application-id=\"local:editor\"]')",'local app and pin survive remount');
  await run("centerClick('本地编辑器')");
  await until('localOpened.length===1','dock launches local app');
  assert.deepEqual(await run('localOpened'),[await run('localAppFixture.path')],'launch receives full path including spaces and Unicode');
  await run("views.requestAppCenter()");
  await until("!!document.querySelector('.app-center-drawer:modal')",'reopen for local app error');
  await pause(220);
  fs.writeFileSync(path.join(output,'app-center-local.png'),(await window.webContents.capturePage()).toPNG());
  await run("localOpenError='应用已移动或不存在';centerClick('本地编辑器')");
  await until("document.querySelector('.app-center-error')?.textContent.includes('应用已移动') && !!document.querySelector('.app-center-drawer:modal')",'launch failure restores drawer with actionable error');
  await run("centerClick('移除 本地编辑器')");
  await until("!document.querySelector('[data-application-id=\"local:editor\"]')",'removing local app also clears its pin');
  assert.equal(await run("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).localApps.length"),0);
  assert.equal(await run('localOpened.length'),1,'removing an entry does not invoke the native app');
  await run("centerClick('关闭应用中心')");
  await until("!document.querySelector('.app-center-drawer')", 'close before restoring an old shortcut');
  await run(`window.refreshedLocalIcons=[];
    window.cardbushDesktop.localApplications.refreshIcons=async paths=>{refreshedLocalIcons.push(paths);return {[localAppFixture.path]:localAppFixture.icon};};
    views.saveAppCenterPreferences({...JSON.parse(localStorage.getItem('cardbush_app_center_v1')),localApps:[{...localAppFixture,title:'我的桌面快捷方式',icon:undefined}],shortcuts:['local:editor']});
    views.requestAppCenter();`);
  await until("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).localApps[0]?.iconVersion===1", 'opening the center refreshes legacy shortcut logos');
  assert.deepEqual(await run('refreshedLocalIcons'), [[await run('localAppFixture.path')]]);
  assert.equal(await run("document.querySelector('.app-center-dock [data-application-id=\"local:editor\"] img').src"), await run('localAppFixture.icon'), 'refreshed logo reaches the dock');
  assert.equal(await run("JSON.parse(localStorage.getItem('cardbush_app_center_v1')).localApps[0].title"), '我的桌面快捷方式', 'refresh retains the user name and pin');
  await run("centerClick('关闭应用中心')");
  await until("!document.querySelector('.app-center-drawer')", 'close refreshed shortcut');
  await run('views.requestAppCenter()');
  await until("!!document.querySelector('.app-center-drawer:modal')", 'reopen refreshed shortcut');
  assert.equal(await run('refreshedLocalIcons.length'), 1, 'persisted native logos do not reload on every open');
  console.log('App center UI passed: desktop shortcut logo migration, local app selection/cancel/deduplication, native icons, launch/errors/removal, dock alignment and hover hold, persistence and native drag, themes, focus, shortcuts, links and non-executing references.');
};
