const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
module.exports = async ({ run, until, click, choose, edit, window: win, root }) => {
  await run(`
    window.agentSettingsCalls=[];window.slowA=false;window.localReads=0;
    const originalRead=cardbushDesktop.readGlobalInstructions;
    cardbushDesktop.readGlobalInstructions=async()=>{localReads++;return originalRead()};
    cardbushDesktop.runtime={command:()=>{throw Error('Remote settings called local Runtime')}};
    cardbushDesktop.productHost={command:()=>{throw Error('Remote settings called local Product Host')}};
    window.remoteModels={a:{defaultModelId:'ma',models:[{id:'ma',provider:'deepseek',modelName:'Remote A',apiKey:'',hasApiKey:true}]},b:{defaultModelId:'mb',models:[{id:'mb',provider:'openai',modelName:'Remote B',apiKey:'',hasApiKey:true}]}};
    window.remoteRules={a:{path:'/srv/a/AGENTS.md',content:'Rules A',revision:'1'},b:{path:'/srv/b/AGENTS.md',content:'Rules B',revision:'1'}};
    window.apps={revision:1,serviceEnabled:true,plugins:[{id:'test-plugin',name:'Remote Plugin',installed:true,enabled:true,source:'user',config:{},components:[],defaultPrompts:[],keywords:[],capabilities:[]}]};
    window.servers=[{id:'remote-mcp',name:'Server tool',enabled:true,transport:'stdio',command:'node',args:['server.js'],description:'',raw:{}}];
    cardbushDesktop.agents={connect:async id=>({id,name:id,platform:'linux',capabilities:{sharedConversation:true,sharedSettings:true}}),call:async(id,operation,input={})=>{
      agentSettingsCalls.push({id,operation,input:structuredClone(input)});
      if(operation==='instructions.get')return {...remoteRules[id]};
      if(operation==='instructions.save'){if(input.revision!==remoteRules[id].revision)throw Error('revision conflict');return remoteRules[id]={...remoteRules[id],...input,revision:'2'}};
      if(operation==='conversation.catalog')return input.action==='read'?{name:input.name,content:'Remote SKILL',path:'/srv/skill',description:''}:{skills:[]};
      if(operation==='mcp.list')return {configuration:{revision:1,servers:servers.map(({id,name,enabled,transport})=>({id,name,enabled,transport}))},runtime:null};
      if(operation==='mcp.configure'){Object.assign(servers.find(s=>s.id===input.id),input);return {saved:true}};
      if(operation==='mcp.reconnect')return {};
      if(operation==='product.command'){
        if(input.kind==='mcp.get')return {revision:1,servers:structuredClone(servers)};
        if(input.kind==='models.get'){if(id==='a'&&slowA)await new Promise(r=>setTimeout(r,500));return structuredClone(remoteModels[id])};
        if(input.kind==='models.update')return remoteModels[id]=input.config;
        if(input.kind==='apps.get')return structuredClone(apps);
        if(input.kind==='apps.update'){apps={...apps,revision:apps.revision+1,plugins:apps.plugins.map(p=>({...p,...input.config.plugins.find(n=>n.id===p.id)}))};return structuredClone(apps)};
        if(input.kind.startsWith('maintenance.'))return {cleared:true,counts:{logs:3}};
      }
      if(operation==='plugins.install')return {id:'test-plugin'};
      if(operation==='projects.list')return {projects:[],defaultProjectId:null};
      throw Error('Unexpected remote settings operation '+operation+' '+input.kind);
    }};
    settingsProps.agentConnections=[{id:'a',name:'Agent A',url:'https://a.invalid'},{id:'b',name:'Agent B',url:'https://b.invalid'}];
    settingsProps.onAgentChange=id=>{settingsProps.agentId=id;renderSettings()};renderSettings();
  `);
  await click('模型管理');
  await choose('.settings-target [role=combobox]', 'a');
  await until("document.querySelector('.model-row')?.textContent.includes('Remote A')");
  assert.equal(await run("document.querySelector('[name=agent-vision-mode] + button').value"), 'inherit');
  await choose('[name=agent-vision-mode] + button', 'on');
  assert.equal(await run("JSON.parse(localStorage.getItem('cardbush-agent-preferences:a')).visionEnabled"), true);
  await choose('[name=agent-vision-mode] + button', 'inherit');
  assert.equal(await run("'visionEnabled' in JSON.parse(localStorage.getItem('cardbush-agent-preferences:a'))"), false);
  await run("settingsProps.visualInputEnabled=true;renderSettings()");
  await until("document.querySelector('[name=agent-vision-mode] + button').textContent.includes('开启')");
  assert.equal(await run("agentSettingsCalls.some(c=>c.operation==='product.command'&&c.input.kind==='models.update')"), false, 'shared preference never writes model credentials');
  await click('个性化');
  await until("document.querySelector('#global-agent-instructions')?.value==='Rules A'");
  const beforeLocal = await run('localReads');
  await edit('#global-agent-instructions', 'Edited rules A', true);
  await run("document.querySelector('.global-instructions-actions .primary-button').click()");
  await until("remoteRules.a.content==='Edited rules A'");
  assert.equal(await run('file.content.includes("Edited")'), false);
  await choose('.settings-target [role=combobox]', 'b');
  await until("document.querySelector('#global-agent-instructions')?.value==='Rules B'");
  assert.equal(await run('localReads'), beforeLocal, 'no local instructions read while switching remote hosts');
  await click('外观与语言');
  assert.ok(await run("document.querySelector('.settings-target').textContent.includes('所有环境共用')"));
  await click('模型管理');
  await until("document.querySelector('.model-row')?.textContent.includes('Remote B')");
  await run('slowA=true');
  await choose('.settings-target [role=combobox]', 'a');
  await choose('.settings-target [role=combobox]', 'b');
  await new Promise(r=>setTimeout(r,600));
  assert.ok(await run("document.querySelector('.model-row')?.textContent.includes('Remote B')"), 'late response cannot replace the current target');
  await click('插件');
  await until("!!document.querySelector('.plugin-added-card')");
  assert.equal(await run("document.querySelector('.plugin-hub-tabs').textContent.includes('账号')"), false);
  await run("[...document.querySelectorAll('.plugin-added-card')].find(b=>b.textContent.includes('Remote Plugin')).click()");
  await until("!!document.querySelector('.plugin-detail-hero .plugin-switch')");
  await run("document.querySelector('.plugin-detail-hero .plugin-switch').click()");
  await until('apps.plugins[0].enabled===false');
  assert.equal(await run("agentSettingsCalls.filter(c=>c.input.kind==='apps.update').at(-1).id"), 'b');
  await run("document.querySelector('[data-plugin-page=plugin] .plugin-back').click()");
  await run("[...document.querySelectorAll('.plugin-added-card')].find(b=>b.textContent.includes('Server tool')).click()");
  await until("document.querySelector('.mcp-editor-panel input[aria-label=名称]')?.value==='Server tool'");
  assert.equal(await run("document.querySelector('.mcp-editor-panel input[aria-label=启动命令]').value"), 'node server.js', 'editor reads the full config rather than the public status projection');
  await edit('.mcp-editor-panel input[aria-label=名称]', 'Updated server');
  await run("[...document.querySelectorAll('.mcp-editor-panel button')].find(b=>b.textContent.includes('保存')).click()");
  await until("servers[0].name==='Updated server'");
  await click('数据与维护');
  await until("document.querySelector('.settings-card h3')?.textContent==='Agent B'");
  await run("window.confirm=()=>true;document.querySelectorAll('.maintenance-action-row button')[1].click()");
  await until("agentSettingsCalls.some(c=>c.id==='b'&&c.input.kind==='maintenance.clear_logs_cache')");
  assert.equal(await run("document.querySelectorAll('.settings-disclosure').length"), 0, 'server maintenance cannot reset local assets');
  await click('模型管理');
  await choose('.settings-target [role=combobox]', '');
  await until("document.querySelectorAll('.model-row').length===2");
  assert.equal(await run("settingsProps.settings.managedModelConfigs[0].modelName"), 'deepseek-v4.1-flash-expires-on-0910');
  await choose('.settings-target [role=combobox]', 'b');
  await until("document.querySelector('.model-row')?.textContent.includes('Remote B')");
  fs.writeFileSync(path.join(root,'tmp/unified-agent-settings.png'),(await win.webContents.capturePage()).toPNG());
  console.log('Unified settings passed: shared preferences, scoped writes, late responses, plugins, MCP and maintenance.');
};
