const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
module.exports = async ({run,until,click,edit,pause=ms=>new Promise(r=>setTimeout(r,ms)),window:win,root}) => {
  await run(`window.agentSettingsCalls=[];
    cardbushDesktop.agents={connect:async()=>{throw Error('Settings must use the shared configuration')},call:async(...args)=>{agentSettingsCalls.push(args);throw Error('Settings must use the shared configuration')}};
    settingsProps.agentConnections=[{id:'a',name:'Cloud A'},{id:'b',name:'Cloud B'}];
    settingsProps.agentId='a';settingsProps.onAgentChange=()=>{throw Error('No environment selector expected')};renderSettings();`);
  await click('个性化');await until("!!document.querySelector('#conversation-style-mode')");
  assert.equal(await run("document.querySelector('.settings-target')===null"),true);
  assert.equal(await run("document.querySelectorAll('.settings-nav').length"),13);
  await edit('#global-agent-instructions','Shared rules for local and cloud.',true);await click('保存');
  await until("file.content==='Shared rules for local and cloud.'");
  await run("settingsProps.agentId='b';renderSettings()");
  await until("document.querySelector('#global-agent-instructions')?.value==='Shared rules for local and cloud.'");
  await click('模型管理');await until("document.querySelectorAll('.model-row').length===2");
  assert.ok(await run("document.querySelector('.settings-content').textContent.includes('deepseek')"));
  assert.equal(await run("document.querySelector('.settings-target')===null"),true);
  await click('外观与语言');await until("!!document.querySelector('[name=theme-mode]')");
  await click('快捷键');await until("!!document.querySelector('[data-shortcut-row]')");
  await click('个性化');await until("!!document.querySelector('#conversation-style-mode')");
  assert.deepEqual(await run('agentSettingsCalls'),[],'all entry points edit the same source; remote synchronization happens at cloud use');
  fs.mkdirSync(path.join(root,'tmp'),{recursive:true});win.webContents.invalidate();await pause(100);
  fs.writeFileSync(path.join(root,'tmp/settings-shared-configuration.png'),(await win.webContents.capturePage(undefined,{stayHidden:true})).toPNG());
  console.log('Unified settings passed: no environment selector, shared models/preferences/rules and legacy route compatibility.');
};
